// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl93pO-XFjpoBDcPe4T9UgHwCcPjnF7hI',
    appId: '1:731306516958:web:5f6e66468ce571ddebfd4f',
    messagingSenderId: '731306516958',
    projectId: 'doga-erp',
    authDomain: 'doga-erp.firebaseapp.com',
    databaseURL: 'https://doga-erp-default-rtdb.firebaseio.com',
    storageBucket: 'doga-erp.appspot.com',
    measurementId: 'G-77QZMBQMWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL5uKq5VwJ49oM-u2TXfW2D-hwzXYFsv8',
    appId: '1:731306516958:android:b96762aed8a3a56eebfd4f',
    messagingSenderId: '731306516958',
    projectId: 'doga-erp',
    databaseURL: 'https://doga-erp-default-rtdb.firebaseio.com',
    storageBucket: 'doga-erp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlbVQ7t2Rv9WsvFxwEf76lhpbhGqfegqo',
    appId: '1:731306516958:ios:9755bb34b3c65eceebfd4f',
    messagingSenderId: '731306516958',
    projectId: 'doga-erp',
    databaseURL: 'https://doga-erp-default-rtdb.firebaseio.com',
    storageBucket: 'doga-erp.appspot.com',
    iosBundleId: 'com.example.dogaErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlbVQ7t2Rv9WsvFxwEf76lhpbhGqfegqo',
    appId: '1:731306516958:ios:9bc4aede613102ecebfd4f',
    messagingSenderId: '731306516958',
    projectId: 'doga-erp',
    databaseURL: 'https://doga-erp-default-rtdb.firebaseio.com',
    storageBucket: 'doga-erp.appspot.com',
    iosBundleId: 'com.example.dogaErp.RunnerTests',
  );
}
